-- Tabla base
CREATE TABLE PERSONA (
    ID_PERSONA     NUMBER PRIMARY KEY,
    NOMBRE         VARCHAR2(50),
    APELLIDO       VARCHAR2(50),
    EDAD           NUMBER,
    CORREO         VARCHAR2(100),
    FECHA_REGISTRO DATE
);

-- Paquete (spec)
CREATE OR REPLACE PACKAGE PKG_PERSONA AS
  PROCEDURE SP_INSERTAR_PERSONA(
    P_ID_PERSONA     IN PERSONA.ID_PERSONA%TYPE,
    P_NOMBRE         IN PERSONA.NOMBRE%TYPE,
    P_APELLIDO       IN PERSONA.APELLIDO%TYPE,
    P_EDAD           IN PERSONA.EDAD%TYPE,
    P_CORREO         IN PERSONA.CORREO%TYPE,
    P_FECHA_REGISTRO IN PERSONA.FECHA_REGISTRO%TYPE
  );

  PROCEDURE SP_ACTUALIZAR_PERSONA(
    P_ID_PERSONA     IN PERSONA.ID_PERSONA%TYPE,
    P_NOMBRE         IN PERSONA.NOMBRE%TYPE,
    P_APELLIDO       IN PERSONA.APELLIDO%TYPE,
    P_EDAD           IN PERSONA.EDAD%TYPE,
    P_CORREO         IN PERSONA.CORREO%TYPE,
    P_FECHA_REGISTRO IN PERSONA.FECHA_REGISTRO%TYPE
  );

  PROCEDURE SP_SELECCIONAR_PERSONA(
    P_ID_PERSONA     IN  PERSONA.ID_PERSONA%TYPE,
    P_NOMBRE         OUT PERSONA.NOMBRE%TYPE,
    P_APELLIDO       OUT PERSONA.APELLIDO%TYPE,
    P_EDAD           OUT PERSONA.EDAD%TYPE,
    P_CORREO         OUT PERSONA.CORREO%TYPE,
    P_FECHA_REGISTRO OUT PERSONA.FECHA_REGISTRO%TYPE
  );

  PROCEDURE SP_ELIMINAR_PERSONA(
    P_ID_PERSONA IN PERSONA.ID_PERSONA%TYPE
  );
END PKG_PERSONA;
/
-- Body
CREATE OR REPLACE PACKAGE BODY PKG_PERSONA AS
  PROCEDURE SP_INSERTAR_PERSONA(
    P_ID_PERSONA     IN PERSONA.ID_PERSONA%TYPE,
    P_NOMBRE         IN PERSONA.NOMBRE%TYPE,
    P_APELLIDO       IN PERSONA.APELLIDO%TYPE,
    P_EDAD           IN PERSONA.EDAD%TYPE,
    P_CORREO         IN PERSONA.CORREO%TYPE,
    P_FECHA_REGISTRO IN PERSONA.FECHA_REGISTRO%TYPE
  ) AS
  BEGIN
    INSERT INTO PERSONA (ID_PERSONA, NOMBRE, APELLIDO, EDAD, CORREO, FECHA_REGISTRO)
    VALUES (P_ID_PERSONA, P_NOMBRE, P_APELLIDO, P_EDAD, P_CORREO, P_FECHA_REGISTRO);
  END;

  PROCEDURE SP_ACTUALIZAR_PERSONA(
    P_ID_PERSONA     IN PERSONA.ID_PERSONA%TYPE,
    P_NOMBRE         IN PERSONA.NOMBRE%TYPE,
    P_APELLIDO       IN PERSONA.APELLIDO%TYPE,
    P_EDAD           IN PERSONA.EDAD%TYPE,
    P_CORREO         IN PERSONA.CORREO%TYPE,
    P_FECHA_REGISTRO IN PERSONA.FECHA_REGISTRO%TYPE
  ) AS
  BEGIN
    UPDATE PERSONA
       SET NOMBRE = P_NOMBRE,
           APELLIDO = P_APELLIDO,
           EDAD = P_EDAD,
           CORREO = P_CORREO,
           FECHA_REGISTRO = P_FECHA_REGISTRO
     WHERE ID_PERSONA = P_ID_PERSONA;
  END;

  PROCEDURE SP_SELECCIONAR_PERSONA(
    P_ID_PERSONA     IN  PERSONA.ID_PERSONA%TYPE,
    P_NOMBRE         OUT PERSONA.NOMBRE%TYPE,
    P_APELLIDO       OUT PERSONA.APELLIDO%TYPE,
    P_EDAD           OUT PERSONA.EDAD%TYPE,
    P_CORREO         OUT PERSONA.CORREO%TYPE,
    P_FECHA_REGISTRO OUT PERSONA.FECHA_REGISTRO%TYPE
  ) AS
  BEGIN
    SELECT NOMBRE, APELLIDO, EDAD, CORREO, FECHA_REGISTRO
      INTO P_NOMBRE, P_APELLIDO, P_EDAD, P_CORREO, P_FECHA_REGISTRO
      FROM PERSONA
     WHERE ID_PERSONA = P_ID_PERSONA;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      P_NOMBRE := NULL;
      P_APELLIDO := NULL;
      P_EDAD := NULL;
      P_CORREO := NULL;
      P_FECHA_REGISTRO := NULL;
  END;

  PROCEDURE SP_ELIMINAR_PERSONA(
    P_ID_PERSONA IN PERSONA.ID_PERSONA%TYPE
  ) AS
  BEGIN
    DELETE FROM PERSONA WHERE ID_PERSONA = P_ID_PERSONA;
  END;
END PKG_PERSONA;
/
